=== juanrita/juanrita.github.io/lm/unidades/unidad7/ejercicio7/ejercicio7.dtd
<!ELEMENT relacion (persona+)>
<!ELEMENT persona (nombre, email*, parentesco?)>
<!ATTLIST persona carnet ID #REQUIRED>
<!ATTLIST persona sexo (hombre | mujer) #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT parentesco EMPTY>
<!ATTLIST parentesco tutor-legal IDREFS #IMPLIED hermano-a IDREFS #IMPLIED>

=== juanrita/juanrita.github.io/lm/unidades/unidad7/ejercicio7/ejercicio7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relacion SYSTEM "ejercicio7.dtd">
<relacion>
  <persona carnet="hijo" sexo="hombre">
   <nombre>Alvaro</nombre>
   <email></email>
   <parentesco tutor-legal="hija" hermano-a="madre" />
  </persona>
  <persona carnet="hija" sexo="mujer">
   <nombre>Antonia</nombre>
   <email></email>
   <parentesco tutor-legal="hijo" hermano-a="hijo" />
  </persona>
  <persona carnet="madre" sexo="mujer">
   <nombre>Lola</nombre>
   <email></email>
   <parentesco tutor-legal="hijo" hermano-a="hijo madre"/>
  </persona>
</relacion>
